### ISSUE TITLE
Decoding without options parses String with quotes as '"some string"'

### ISSUE THREAD

**Issue by koluris** [xan105/node-ini#1]
I have a couple of strings in the .ini file such as:
`hello = "some string"`

and I endup parsing those, such as '"some string"', which makes it impossible for me to use those untouched in a Database for example.

Am I doing something wrong with parsing?

**Comment by xan105** [comment]
Firstly thank you for trying out my module ^_^. But I'm kinda still working on it and I had put it on the back burner due to time.
So forgive me if my answer may lack precision.

The problem with the .ini file format is that there are multiple implementation.
In the base format a string shouldn't be in between `"` if said `"` isn't wanted. 
A key has a name and a value delimited by an equals sign (=) which with the semicolon (on Windows) are reserved characters and cannot appear in the key.

Some implementations allow values to be quoted. The Windows one supports this, and will remove quotation marks that surround the values for ex.

Tbh I don't remember my decision making at the time regarding this. But I do understand your issue. 
I suppose it would be wise to at least have a flag option to control the behavior: do nothing or remove leading and trailing quotes (double quotes and/or apostrophes).

Meanwhile, a simple `string.replace(/^\"|\"$/g,"")` would get rid of them if that's helpful.

**Comment by koluris** [comment]
Thanks for explanation. I will be completely honest, I switched from npm's `ini` to your module, because it could not parse booleans properly. So one problem is the one mentioned above, and the next one is that it adds a unwanted extra `\` on a specific type of string, for example:

`hello = "some_string\u0000"` becomes `'"some_string\\u0000"'` after parsing.

Other than that, I wanted to let you know that it seems promising overall.

**Comment by xan105** [comment]
I understand, I built this because of some grievances I had with npm's ini module (and others as well).

Ok so I just saw in [my own doc](https://github.com/xan105/node-ini#auto-type) 😂 that I already have a switch for this issue 😅.

```js
ini.parse(string, {autoType : { //granular autotype
  unquote: true //Remove leading and trailing quote (" or ') in a string value
}
});
```

As for the 2nd issue, are you sure it is an issue ?
`\` is an illegal char in js as it is use to escape other char thus the symbol `\` will be escaped to `\\` but when like writing to a file and etc `\\` will be `\` at the end.
